# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 7.1
  - 7.2

services:
    - mysql
    - riak
    - mongodb
    - memcached
    - redis-server
    - docker
    
env:
  - YII_VERSION="2.0.*"

before_install:
    - pecl channel-update pecl.php.net
    - echo yes | pecl upgrade apcu
    - phpenv config-add ./tests/_travis/php.ini
    - mysql -e 'CREATE DATABASE abexto_amylian_tests';
    - mysql -e "GRANT ALL PRIVILEGES ON abexto_amylian_tests.* to 'travis'@'%'";

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
  - composer require yiisoft/yii2:${YII_VERSION}
  
before_script:
  - cp tests/_travis/phpunit.xml phpunit.xml

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS